# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20180321_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
