# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_auto_20180321_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='desc',
            new_name='description',
        ),
    ]
